# -*- coding: utf-8 -*-
"""DOTE 6756_EnglishPremierLeague.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eSYB_i0Iv8WQmj8_eyCOXwm77EsQiBy
"""

# Import google plugs
!pip install gdown
import gdown
file_id = "1-NcAiQ_EFzEtlkzod-KvNqjOZpeO-xUE"
url = f"https://drive.google.com/uc?id={file_id}"
gdown.download(url, "england.csv", quiet=False)


#Import numpy and pandas
import numpy as np
import pandas as pd

#Download the CSV files
engpremier=pd.read_csv("england.csv")

#Display the first 5 rows of Eng Preimer Dataset
engpremier.head()

engpremier.info()

#Drop columns
columns_to_drop = ['Date', 'Referee','Display_Order','League']
engpremier_cut = engpremier.drop(columns_to_drop, axis=1)

engpremier_cut.head()

#Filter rows before 2000/01 as no data on shots,fouls,corners,card etc...
engpremier_filter=engpremier_cut.loc[
    (engpremier_cut['Season']!='1999/00')&
    (engpremier_cut['Season']!='1998/99')&
    (engpremier_cut['Season']!='1997/98')&
    (engpremier_cut['Season']!='1996/97')&
    (engpremier_cut['Season']!='1995/96')&
    (engpremier_cut['Season']!='1994/95')&
    (engpremier_cut['Season']!='1993/94')]

engpremier_filter

#Compute Fundamental Descriptive Statistics for FT Goals

#Extract FTH Goals column from the filtered dataset
eng_FTH_goals=engpremier_filter['FTH Goals']
eng_FTH_goals.head()

print("FTH Goals Summary:\n", eng_FTH_goals.describe())

#Extract FTA Goals column from the filtered dataset
eng_FTA_goals=engpremier_filter['FTA Goals']
eng_FTA_goals.head()

print("FTA Goals Summary:\n", eng_FTA_goals.describe())

#Counts of FT Results
FT_counts = engpremier_filter['FT Result'].value_counts()
print(FT_counts)

#Compute Fundamental Descriptive Statistics for HT Goals

#Extract HTH Goals column from the filtered dataset
eng_HTH_goals=engpremier_filter['HTH Goals']
eng_HTH_goals.head()

print("HTH Goals Summary:\n", eng_HTH_goals.describe())

#Extract HTA Goals column from the filtered dataset
eng_HTA_goals=engpremier_filter['HTA Goals']
eng_HTA_goals.head()

print("HTA Goals Summary:\n", eng_HTA_goals.describe())

#Counts of HT Results
HT_counts = engpremier_filter['HT Result'].value_counts()
print(HT_counts)

import matplotlib.pyplot as plt
import seaborn as sns

#Create a new column to sum up the total goals of Full Time Result
engpremier_filter['FT_total_goals'] = engpremier_filter['FTH Goals'] + engpremier_filter['FTA Goals']
engpremier_filter

#Create a new column to sum up the total goals of Half Time Result
engpremier_filter['HT_total_goals'] = engpremier_filter['HTH Goals'] + engpremier_filter['HTA Goals']
engpremier_filter

#Create a new column to calculate the total goals of Second Half Time Result
engpremier_filter['SHT_total_goals'] = engpremier_filter['FTH Goals']+ engpremier_filter['FTA Goals']- engpremier_filter['HTH Goals']- engpremier_filter['HTA Goals']
engpremier_filter

#⁠Home VS Away winning correlation , does home stadium have an advantage to win ?
counts = engpremier_filter['FT Result'].value_counts()

# create a canvas
fig,ax=plt.subplots()

# draw a count bar plot
counts.plot(kind='bar', color='skyblue')
plt.xlabel('Full Time Result')
plt.ylabel('Counts')
plt.title('Full Time Result vs Counts')
plt.show()

#Goal happening on half time more vs second half time more leading to win ?

categories = engpremier_filter['FT Result']
series=engpremier_filter['FT_total_goals']
series1 = engpremier_filter['HT_total_goals']
series2 = engpremier_filter['SHT_total_goals']

fig, ax = plt.subplots()

sns.histplot(data=engpremier_filter, x=series1, hue=categories, weights=series, multiple='stack', shrink=0.8)

plt.show()

sns.histplot(data=engpremier_filter, x=series2, hue=categories, weights=series, multiple='stack', shrink=0.8)

plt.show()

total_HT = sum(engpremier_filter['HT_total_goals'])
print("Total HT Goals:\n",total_HT)

total_SHT = sum(engpremier_filter['SHT_total_goals'])
print("Total SHT Goals:\n",total_SHT)

#Does more attempted shots lead to higher scoring chance ?( with target shots rate )

# create a canvas
fig, ax = plt.subplots()

Hshots=engpremier_filter['H Shots']
HSOT= engpremier_filter['H SOT']
HShot_Accuracy = (HSOT / Hshots) * 100

# draw a line plot
sns.lineplot(
    data=engpremier_filter,
    x=Hshots,
    y=HShot_Accuracy,
    ax=ax
)

plt.ylabel('Accuracy %')
plt.title('Trend of Accuracy % over H Shots')
plt.show()

# create a canvas
fig, ax = plt.subplots()

Ashots=engpremier_filter['A Shots']
ASOT= engpremier_filter['A SOT']
AShot_Accuracy = (ASOT / Ashots) * 100

# draw a line plot
sns.lineplot(
    data=engpremier_filter,
    x=Ashots,
    y=AShot_Accuracy,
    ax=ax
)

plt.ylabel('Accuracy %')
plt.title('Trend of Accuracy % over A Shots')
plt.show()

#No of fouls on affecting the winning chance
import statistics

Haverage = statistics.mean(engpremier_filter['H Fouls'])
print(f"H Fouls Average: {Haverage}")


Aaverage = statistics.mean(engpremier_filter['A Fouls'])
print(f"A Fouls Average: {Aaverage}")

TotalFouls= engpremier_filter['H Fouls'] + engpremier_filter['A Fouls']

# create a canvas
fig,ax=plt.subplots()

# draw a box plot
sns.boxplot(
    data=engpremier_filter,
    x=categories,
    y=TotalFouls,
    ax=ax
)

ax.set_ylabel("Total Fouls")
ax.set_title("FT Result vs Total Fouls ")
plt.show()

#⁠Yellow card , red card for winning chance impact

import statistics

HYaverage = statistics.mean(engpremier_filter['H Yellow'])
print(f"H Yellow Average: {HYaverage}")


AYaverage = statistics.mean(engpremier_filter['A Yellow'])
print(f"A Yellow Average: {AYaverage}")

TotalYellow= engpremier_filter['H Yellow'] + engpremier_filter['A Yellow']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalYellow,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Yellow Cards')
plt.title('Total Yellow Cards vs FT Result')

plt.show()

HRaverage = statistics.mean(engpremier_filter['H Red'])
print(f"H Red Average: {HRaverage}")


ARaverage = statistics.mean(engpremier_filter['A Red'])
print(f"A Red Average: {ARaverage}")

TotalRed= engpremier_filter['H Red'] + engpremier_filter['A Red']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalRed,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Red Cards')
plt.title('Total Red Cards vs FT Result')

plt.show()

#Corners affecting the winning chance

import statistics

HCaverage = statistics.mean(engpremier_filter['H Corners'])
print(f"H Corners Average: {HCaverage}")


ACaverage = statistics.mean(engpremier_filter['A Corners'])
print(f"A Corners Average: {ACaverage}")

TotalCorners= engpremier_filter['H Corners'] + engpremier_filter['A Corners']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalCorners,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Corners')
plt.title('Total Corners vs FT Result')

plt.show()

"""Random Forest"""

from sklearn.ensemble import RandomForestRegressor

# Define predictors and target
X = engpremier_filter[['H Shots', 'A Shots', 'H SOT', 'A SOT',
                       'H Fouls', 'A Fouls', 'H Yellow', 'A Yellow',
                       'H Red', 'A Red', 'H Corners', 'A Corners']]
y = engpremier_filter['FT_total_goals']

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X, y)
# Predict on the same data (like in Lesson 10)
y_pred = rf_model.predict(X)

# Print first 5 predictions
print("Predicted FT_total_goals:\n", y_pred[:5])

"""The Winning Factors to the English Premier League (EPL):  
Leveraging Clustering Methods to Enhance Predictive Accuracy and Strategic Decisions
"""

#-------- Config knobs  -------
features = ['H Shots','A Shots','H SOT','A SOT','H Fouls','A Fouls',
      'H Yellow','A Yellow','H Red','A Red','H Corners','A Corners']

K_RANGE = range(2, 11)
PCA_COMPONENTS = 2
DBSCAN_EPS = 1.2
DBSCAN_MIN_SAMPLES = 10
RANDOM_STATE = 42

# ============================================================
# CLUSTERING RUN 1: PURE (no target leakage)
# ============================================================
print("\n[RUN 1] Computing PURE clusters (base statistics only)...\n")

# Use only base features (no goals)
cluster_features_pure = features.copy()

X_pure_raw = engpremier_filter[cluster_features_pure].apply(pd.to_numeric, errors='coerce')

imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()

X_pure_filled = imputer.fit_transform(X_pure_raw)
X_pure_scaled = scaler.fit_transform(X_pure_filled)

print(f"[Pure] Clustering data: {X_pure_scaled.shape[0]} rows x {X_pure_scaled.shape[1]} features")

# Find best k using silhouette
inertias_pure = []
sil_scores_pure = []
for k in K_RANGE:
    kmeans_temp = KMeans(n_clusters=k, random_state=RANDOM_STATE)
    kmeans_temp.fit(X_pure_scaled)
    inertias_pure.append(kmeans_temp.inertia_)
    sil_score = silhouette_score(X_pure_scaled, kmeans_temp.labels_)
    sil_scores_pure.append(sil_score)
    print(f"  k={k}: silhouette = {sil_score:.3f}")

best_k_pure = list(K_RANGE)[int(np.argmax(sil_scores_pure))]
print(f"\n[Pure] Best k by silhouette: {best_k_pure}")

kmeans_pure = KMeans(n_clusters=best_k_pure, random_state=RANDOM_STATE, n_init=10)
engpremier_filter['cluster_km_pure'] = kmeans_pure.fit_predict(X_pure_scaled)
print(f"[Pure] Silhouette score: {silhouette_score(X_pure_scaled, engpremier_filter['cluster_km_pure']):.3f}")

# Visualize
pca_pure = PCA(n_components=2, random_state=RANDOM_STATE)
X_2d_pure = pca_pure.fit_transform(X_pure_scaled)

plt.figure(figsize=(6,5))
sns.scatterplot(x=X_2d_pure[:,0], y=X_2d_pure[:,1], hue=engpremier_filter['cluster_km_pure'], palette='tab10', s=35, alpha=0.85)
plt.title('K-Means Pure Clusters (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ============================================================
# CLUSTERING RUN 2: ENGINEERED (with goal variables - for comparison)
# ============================================================
print("\n[RUN 2] Computing ENGINEERED clusters (includes goal variables)...\n")

cluster_features_eng = features + ['FT_total_goals','HT_total_goals','SHT_total_goals']

X_eng_raw = engpremier_filter[cluster_features_eng].apply(pd.to_numeric, errors='coerce')

imputer_eng = SimpleImputer(strategy='median')
scaler_eng = StandardScaler()

X_eng_filled = imputer_eng.fit_transform(X_eng_raw)
X_eng_scaled = scaler_eng.fit_transform(X_eng_filled)

print(f"[Engineered] Clustering data: {X_eng_scaled.shape[0]} rows x {X_eng_scaled.shape[1]} features")

# Find best k
inertias_eng = []
sil_scores_eng = []
for k in K_RANGE:
    kmeans_temp = KMeans(n_clusters=k, random_state=RANDOM_STATE)
    kmeans_temp.fit(X_eng_scaled)
    inertias_eng.append(kmeans_temp.inertia_)
    sil_score = silhouette_score(X_eng_scaled, kmeans_temp.labels_)
    sil_scores_eng.append(sil_score)
    print(f"  k={k}: silhouette = {sil_score:.3f}")

best_k_eng = list(K_RANGE)[int(np.argmax(sil_scores_eng))]
print(f"\n[Engineered] Best k by silhouette: {best_k_eng}")

kmeans_eng = KMeans(n_clusters=best_k_eng, random_state=RANDOM_STATE, n_init=10)
engpremier_filter['cluster_km_engineered'] = kmeans_eng.fit_predict(X_eng_scaled)
print(f"[Engineered] Silhouette score: {silhouette_score(X_eng_scaled, engpremier_filter['cluster_km_engineered']):.3f}")

# Visualize
pca_eng = PCA(n_components=2, random_state=RANDOM_STATE)
X_2d_eng = pca_eng.fit_transform(X_eng_scaled)

plt.figure(figsize=(6,5))
sns.scatterplot(x=X_2d_eng[:,0], y=X_2d_eng[:,1], hue=engpremier_filter['cluster_km_engineered'], palette='tab10', s=35, alpha=0.85)
plt.title('K-Means Engineered Clusters (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ============================================================
# MODEL COMPARISON: Pure vs Engineered
# ============================================================
print("\n[COMPARISON] Training models with each clustering approach...\n")

# Define base features for modeling
base_feats = [
    'H Shots','A Shots','H SOT','A SOT',
    'H Fouls','A Fouls','H Yellow','A Yellow',
    'H Red','A Red','H Corners','A Corners'
]

y_model = engpremier_filter['FT_total_goals'].copy()

# Model 1: Pure clusters
rf_feats_pure = base_feats + ['cluster_km_pure']
X_pure_model = engpremier_filter[rf_feats_pure].dropna()
y_pure_model = engpremier_filter.loc[X_pure_model.index, 'FT_total_goals']

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(X_pure_model, y_pure_model, test_size=0.2, random_state=RANDOM_STATE)

rf_pure_model = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
rf_pure_model.fit(X_train_p, y_train_p)
r2_pure = rf_pure_model.score(X_test_p, y_test_p)

print(f"Model 1 - R² with PURE clusters:       {r2_pure:.4f}")

# Model 2: Engineered clusters
rf_feats_eng = base_feats + ['cluster_km_engineered']
X_eng_model = engpremier_filter[rf_feats_eng].dropna()
y_eng_model = engpremier_filter.loc[X_eng_model.index, 'FT_total_goals']

X_train_e, X_test_e, y_train_e, y_test_e = train_test_split(X_eng_model, y_eng_model, test_size=0.2, random_state=RANDOM_STATE)

rf_eng_model = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
rf_eng_model.fit(X_train_e, y_train_e)
r2_eng = rf_eng_model.score(X_test_e, y_test_e)

print(f"Model 2 - R² with ENGINEERED clusters: {r2_eng:.4f}")
print(f"\nLeakage effect (difference): {r2_eng - r2_pure:+.4f}")

if abs(r2_eng - r2_pure) < 0.05:
    print("✓ Small difference = genuine clustering signal, not leakage")
else:
    print("✗ Large difference = significant leakage detected")
    print("   → Use PURE clusters for honest model evaluation")

# Feature importance comparison
print("\n[Pure Model] Feature importances:")
imp_pure = pd.Series(rf_pure_model.feature_importances_, index=rf_feats_pure).sort_values(ascending=False)
print(imp_pure.round(4))

print("\n[Engineered Model] Feature importances:")
imp_eng = pd.Series(rf_eng_model.feature_importances_, index=rf_feats_eng).sort_values(ascending=False)
print(imp_eng.round(4))

