# -*- coding: utf-8 -*-
"""DOTE 6756_EnglishPremierLeague.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eSYB_i0Iv8WQmj8_eyCOXwm77EsQiBy
"""

# Import google plugs
!pip install gdown
import gdown
file_id = "1-NcAiQ_EFzEtlkzod-KvNqjOZpeO-xUE"
url = f"https://drive.google.com/uc?id={file_id}"
gdown.download(url, "england.csv", quiet=False)


#Import numpy and pandas
import numpy as np
import pandas as pd

#Download the CSV files
engpremier=pd.read_csv("england.csv")

#Display the first 5 rows of Eng Preimer Dataset
engpremier.head()

engpremier.info()

#Drop columns
columns_to_drop = ['Date', 'Referee','Display_Order','League']
engpremier_cut = engpremier.drop(columns_to_drop, axis=1)

engpremier_cut.head()

#Filter rows before 2000/01 as no data on shots,fouls,corners,card etc...
engpremier_filter=engpremier_cut.loc[
    (engpremier_cut['Season']!='1999/00')&
    (engpremier_cut['Season']!='1998/99')&
    (engpremier_cut['Season']!='1997/98')&
    (engpremier_cut['Season']!='1996/97')&
    (engpremier_cut['Season']!='1995/96')&
    (engpremier_cut['Season']!='1994/95')&
    (engpremier_cut['Season']!='1993/94')]

engpremier_filter

#Compute Fundamental Descriptive Statistics for FT Goals

#Extract FTH Goals column from the filtered dataset
eng_FTH_goals=engpremier_filter['FTH Goals']
eng_FTH_goals.head()

print("FTH Goals Summary:\n", eng_FTH_goals.describe())

#Extract FTA Goals column from the filtered dataset
eng_FTA_goals=engpremier_filter['FTA Goals']
eng_FTA_goals.head()

print("FTA Goals Summary:\n", eng_FTA_goals.describe())

#Counts of FT Results
FT_counts = engpremier_filter['FT Result'].value_counts()
print(FT_counts)

#Compute Fundamental Descriptive Statistics for HT Goals

#Extract HTH Goals column from the filtered dataset
eng_HTH_goals=engpremier_filter['HTH Goals']
eng_HTH_goals.head()

print("HTH Goals Summary:\n", eng_HTH_goals.describe())

#Extract HTA Goals column from the filtered dataset
eng_HTA_goals=engpremier_filter['HTA Goals']
eng_HTA_goals.head()

print("HTA Goals Summary:\n", eng_HTA_goals.describe())

#Counts of HT Results
HT_counts = engpremier_filter['HT Result'].value_counts()
print(HT_counts)

import matplotlib.pyplot as plt
import seaborn as sns

#Create a new column to sum up the total goals of Full Time Result
engpremier_filter['FT_total_goals'] = engpremier_filter['FTH Goals'] + engpremier_filter['FTA Goals']
engpremier_filter

#Create a new column to sum up the total goals of Half Time Result
engpremier_filter['HT_total_goals'] = engpremier_filter['HTH Goals'] + engpremier_filter['HTA Goals']
engpremier_filter

#Create a new column to calculate the total goals of Second Half Time Result
engpremier_filter['SHT_total_goals'] = engpremier_filter['FTH Goals']+ engpremier_filter['FTA Goals']- engpremier_filter['HTH Goals']- engpremier_filter['HTA Goals']
engpremier_filter

#⁠Home VS Away winning correlation , does home stadium have an advantage to win ?
counts = engpremier_filter['FT Result'].value_counts()

# create a canvas
fig,ax=plt.subplots()

# draw a count bar plot
counts.plot(kind='bar', color='skyblue')
plt.xlabel('Full Time Result')
plt.ylabel('Counts')
plt.title('Full Time Result vs Counts')
plt.show()

#Goal happening on half time more vs second half time more leading to win ?

categories = engpremier_filter['FT Result']
series=engpremier_filter['FT_total_goals']
series1 = engpremier_filter['HT_total_goals']
series2 = engpremier_filter['SHT_total_goals']

fig, ax = plt.subplots()

sns.histplot(data=engpremier_filter, x=series1, hue=categories, weights=series, multiple='stack', shrink=0.8)

plt.show()

sns.histplot(data=engpremier_filter, x=series2, hue=categories, weights=series, multiple='stack', shrink=0.8)

plt.show()

total_HT = sum(engpremier_filter['HT_total_goals'])
print("Total HT Goals:\n",total_HT)

total_SHT = sum(engpremier_filter['SHT_total_goals'])
print("Total SHT Goals:\n",total_SHT)

#Does more attempted shots lead to higher scoring chance ?( with target shots rate )

# create a canvas
fig, ax = plt.subplots()

Hshots=engpremier_filter['H Shots']
HSOT= engpremier_filter['H SOT']
HShot_Accuracy = (HSOT / Hshots) * 100

# draw a line plot
sns.lineplot(
    data=engpremier_filter,
    x=Hshots,
    y=HShot_Accuracy,
    ax=ax
)

plt.ylabel('Accuracy %')
plt.title('Trend of Accuracy % over H Shots')
plt.show()

# create a canvas
fig, ax = plt.subplots()

Ashots=engpremier_filter['A Shots']
ASOT= engpremier_filter['A SOT']
AShot_Accuracy = (ASOT / Ashots) * 100

# draw a line plot
sns.lineplot(
    data=engpremier_filter,
    x=Ashots,
    y=AShot_Accuracy,
    ax=ax
)

plt.ylabel('Accuracy %')
plt.title('Trend of Accuracy % over A Shots')
plt.show()

#No of fouls on affecting the winning chance
import statistics

Haverage = statistics.mean(engpremier_filter['H Fouls'])
print(f"H Fouls Average: {Haverage}")


Aaverage = statistics.mean(engpremier_filter['A Fouls'])
print(f"A Fouls Average: {Aaverage}")

TotalFouls= engpremier_filter['H Fouls'] + engpremier_filter['A Fouls']

# create a canvas
fig,ax=plt.subplots()

# draw a box plot
sns.boxplot(
    data=engpremier_filter,
    x=categories,
    y=TotalFouls,
    ax=ax
)

ax.set_ylabel("Total Fouls")
ax.set_title("FT Result vs Total Fouls ")
plt.show()

#⁠Yellow card , red card for winning chance impact

import statistics

HYaverage = statistics.mean(engpremier_filter['H Yellow'])
print(f"H Yellow Average: {HYaverage}")


AYaverage = statistics.mean(engpremier_filter['A Yellow'])
print(f"A Yellow Average: {AYaverage}")

TotalYellow= engpremier_filter['H Yellow'] + engpremier_filter['A Yellow']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalYellow,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Yellow Cards')
plt.title('Total Yellow Cards vs FT Result')

plt.show()

HRaverage = statistics.mean(engpremier_filter['H Red'])
print(f"H Red Average: {HRaverage}")


ARaverage = statistics.mean(engpremier_filter['A Red'])
print(f"A Red Average: {ARaverage}")

TotalRed= engpremier_filter['H Red'] + engpremier_filter['A Red']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalRed,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Red Cards')
plt.title('Total Red Cards vs FT Result')

plt.show()

#Corners affecting the winning chance

import statistics

HCaverage = statistics.mean(engpremier_filter['H Corners'])
print(f"H Corners Average: {HCaverage}")


ACaverage = statistics.mean(engpremier_filter['A Corners'])
print(f"A Corners Average: {ACaverage}")

TotalCorners= engpremier_filter['H Corners'] + engpremier_filter['A Corners']

# create a canvas
fig,ax=plt.subplots()

# draw a bar plot
sns.barplot(
    data=engpremier_filter,
    x=categories,
    y=TotalCorners,
    ax=ax
)

plt.xlabel('FT Result')
plt.ylabel('Total Corners')
plt.title('Total Corners vs FT Result')

plt.show()

"""Random Forest"""

from sklearn.ensemble import RandomForestRegressor

# Define predictors and target
X = engpremier_filter[['H Shots', 'A Shots', 'H SOT', 'A SOT',
                       'H Fouls', 'A Fouls', 'H Yellow', 'A Yellow',
                       'H Red', 'A Red', 'H Corners', 'A Corners']]
y = engpremier_filter['FT_total_goals']

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X, y)
# Predict on the same data (like in Lesson 10)
y_pred = rf_model.predict(X)

# Print first 5 predictions
print("Predicted FT_total_goals:\n", y_pred[:5])

"""The Winning Factors to the English Premier League (EPL):  
Leveraging Clustering Methods to Enhance Predictive Accuracy and Strategic Decisions
"""

#-------- Config knobs  -------
# Features I'm using for clustering - mostly match statistics
features = ['H Shots','A Shots','H SOT','A SOT','H Fouls','A Fouls',
      'H Yellow','A Yellow','H Red','A Red','H Corners','A Corners']

# Try different k values to find best clusters
# engineered totals below are optional (toggle INCLUDE_ENGINEERED plz)

INCLUDE_ENGINEERED = True  # include FT_total_goals, HT_total_goals, SHT_total_goals in clustering
K_RANGE = range(2, 11)     # candidate k for KMeans elbow/silhouette
PCA_COMPONENTS = 2         # 2D plot for visualization
DBSCAN_EPS = 1.2            # had to tune this - started with 0.5 but got too many outliers
DBSCAN_MIN_SAMPLES = 10    # typical range: 5–15
RANDOM_STATE = 42          # reproducibility for KMeans, PCA, RF
# ------------------------------------------------

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

sns.set(style='whitegrid', rc={"axes.spines.right": False, "axes.spines.top": False})

# -----------------------
# 0) Safety
# ---------------------------
# Work on a defensive copy to avoid SettingWithCopy warnings downstream
#if 'H Shots' in data and 'H SOT' in data:
#    data['H_Accuracy_pct'] = np.where(data['H Shots'] > 0,
#                                      100 * data['H SOT'] / data['H Shots'], np.nan)
#if 'A Shots' in data and 'A SOT' in data:
#    data['A_Accuracy_pct'] = np.where(data['A Shots'] > 0,
#                                      100 * data['A SOT'] / data['A Shots'], np.nan)

# ------------------------------------
# 1) Define clustering feature matrix
# ------------------------------------

# Add the goal columns I created earlier
cluster_features = features.copy()
cluster_features.extend(['FT_total_goals','HT_total_goals','SHT_total_goals'])

# Convert to numbers (some might be strings)
X_raw = data[cluster_features].apply(pd.to_numeric, errors='coerce')

# -----------------------------------
# 2) Preprocess: impute + scale
# Need to handle missing values and scale everything
# Using median because some outliers in the data
imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()

X_filled = imputer.fit_transform(X_raw)
X = scaler.fit_transform(X_filled)  # scale so shots don't dominate over cards


scaled_feature_names = cluster_features  # for centroid interpretation
print(f"[Info] Clustering data: {X.shape[0]} rows x {X.shape[1]} features")

# -------------------------------
# 3) K-Means elbow + silhouette
# -------------------------------



# Test different numbers of clusters to find the best one
inertias = []
sil_scores = []
for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertias.append(kmeans.inertia_)

    # Calculate silhouette score - higher is better
    sil_score = silhouette_score(X, kmeans.labels_)
    sil_scores.append(sil_score)
    print(f"k={k}: silhouette = {sil_score:.3f}")  # see results as I go

#Elbow: plots inertia (SSE) to see where adding more clusters doesn’t help much.
plt.figure(figsize=(6,4))
plt.plot(list(K_RANGE), inertias, marker='o')
plt.xlabel('k')
plt.ylabel('Inertia (SSE)')
plt.title('Elbow Curve (K-Means)')
plt.show()


#Silhouette: scores how well points fit inside their assigned cluster vs. the next best cluster.
plt.figure(figsize=(6,4))
plt.plot(list(K_RANGE), sil_scores, marker='o', color='darkgreen')
plt.xlabel('k')
plt.ylabel('Silhouette score')
plt.title('Silhouette vs k')
plt.show()

best_k = list(K_RANGE)[int(np.argmax(sil_scores))]
print(f"[Info] Chosen k by silhouette: {best_k}")

# Fit final KMeans
kmeans = KMeans(n_clusters=best_k, random_state=RANDOM_STATE, n_init=10)
labels_km = kmeans.fit_predict(X)
data['cluster_km'] = labels_km
print("[Info] Silhouette (chosen k):", silhouette_score(X, labels_km))

# --------------------------------
# 4) 2D visualization (PCA)
# -------------------------------
pca = PCA(n_components=PCA_COMPONENTS, random_state=RANDOM_STATE)
X_2d = pca.fit_transform(X)

plt.figure(figsize=(6,5))
sns.scatterplot(x=X_2d[:,0], y=X_2d[:,1], hue=labels_km, palette='tab10', s=35, alpha=0.85)
plt.title('K-Means clusters (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='cluster', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0)
plt.tight_layout()
plt.show()

# def create_separate_business_charts():
#     # 1. Broadcasting Portfolio Distribution
#     fig1, ax1 = plt.subplots(figsize=(8, 6))
#     clusters = list(cluster_data.keys())
#     sizes = [cluster_data[c]['size_pct'] for c in clusters]
#     goals = [cluster_data[c]['goals'] for c in clusters]
#     colors = ['lightgray', 'orange', 'darkred', 'lightgray', 'gold']

#     bars1 = ax1.bar(clusters, sizes, color=colors)
#     ax1.set_title('Broadcasting Portfolio Distribution', fontweight='bold', fontsize=14)
#     ax1.set_ylabel('Market Share (%)')
#     ax1.set_xlabel('Clusters')

#     for bar, goal in zip(bars1, goals):
#         ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
#                 f'{goal:.1f} goals', ha='center', va='bottom', fontsize=9)
#     plt.tight_layout()
#     plt.savefig('broadcasting_portfolio.png', dpi=300, bbox_inches='tight')
#     plt.show()
#     # 2. Betting Success Rates
#     fig2, ax2 = plt.subplots(figsize=(8, 6))
#     home_rates = [cluster_data[c]['home_win'] for c in clusters]
#     away_rates = [cluster_data[c]['away_win'] for c in clusters]

#     x = np.arange(len(clusters))
#     width = 0.35

#     ax2.bar(x - width/2, home_rates, width, label='Home Win %', color='blue', alpha=0.7)
#     ax2.bar(x + width/2, away_rates, width, label='Away Win %', color='red', alpha=0.7)

#     ax2.set_title('Betting Success Rates', fontweight='bold', fontsize=14)
#     ax2.set_ylabel('Win Probability (%)')
#     ax2.set_xticks(x)
#     ax2.set_xticklabels(clusters)
#     ax2.legend()
#     ax2.axhline(y=50, color='black', linestyle='--', alpha=0.5)
#     plt.tight_layout()
#     plt.savefig('betting_success_rates.png', dpi=300, bbox_inches='tight')
#     plt.show()

#     # 3. Goals Markets Strategy
#     fig3, ax3 = plt.subplots(figsize=(8, 6))
#     goals_data = [cluster_data[c]['goals'] for c in clusters]
#     bar_colors = ['red' if g < 2.5 else 'yellow' if g < 3.0 else 'green' for g in goals_data]

#     bars3 = ax3.bar(clusters, goals_data, color=bar_colors)
#     ax3.set_title('Goals Markets Strategy', fontweight='bold', fontsize=14)
#     ax3.set_ylabel('Average Goals')
#     ax3.axhline(y=2.5, color='orange', linestyle='--', alpha=0.7, label='O/U 2.5 Line')
#     ax3.axhline(y=3.5, color='green', linestyle='--', alpha=0.7, label='O/U 3.5 Line')
#     ax3.legend()

#     for bar, goal in zip(bars3, goals_data):
#         ax3.text(bar.get_x() + bar.get_width()/2, goal + 0.05,
#                 f'{goal:.2f}', ha='center', va='bottom', fontweight='bold')
#     plt.tight_layout()
#     plt.savefig('goals_markets_strategy.png', dpi=300, bbox_inches='tight')
#     plt.show()

#     # 4. Strategic Advantages
#     fig4, ax4 = plt.subplots(figsize=(8, 6))
#     advantages = {
#         'C0': 'Away Success',
#         'C1': 'Draw Mastery',
#         'C2': 'Home Physical',
#         'C3': 'Away Attack',
#         'C4': 'Home Dominance'
#     }

#     advantage_scores = [
#         cluster_data['C0']['away_win'],
#         cluster_data['C1']['draw'],
#         cluster_data['C2']['home_win'],
#         cluster_data['C3']['away_win'],
#         cluster_data['C4']['home_win']
#     ]

#     bars4 = ax4.barh(list(advantages.values()), advantage_scores, color=colors)
#     ax4.set_title('Strategic Advantages by Cluster', fontweight='bold', fontsize=14)
#     ax4.set_xlabel('Success Rate (%)')

#     for bar, score in zip(bars4, advantage_scores):
#         ax4.text(score + 1, bar.get_y() + bar.get_height()/2,
#                 f'{score:.1f}%', va='center', fontweight='bold')
#     plt.tight_layout()
#     plt.savefig('strategic_advantages.png', dpi=300, bbox_inches='tight')
#     plt.show()

# # Call the function
# create_separate_business_charts()

# ---------------------------------------------------------
# 5) Centroid profiles (inverse transform to original scale)
# -------------------------------------------------------
scaler = preprocess.named_transformers_['num'].named_steps['scaler']
centroids_scaled = kmeans.cluster_centers_
centroids_imputed = scaler.inverse_transform(centroids_scaled)
centroids_df = pd.DataFrame(centroids_imputed, columns=scaled_feature_names)
centroids_df.index.name = 'cluster'
centroids_df = centroids_df.reset_index()
print("[Info] Centroids (original scale):")
display(centroids_df.round(2))


# Bar chart of centroids across features
melted = centroids_df.melt(id_vars='cluster', var_name='feature', value_name='value')
plt.figure(figsize=(10,6))
sns.barplot(data=melted, x='feature', y='value', hue='cluster')
plt.xticks(rotation=45, ha='right')
plt.title('Cluster profiles')
plt.tight_layout()
plt.show()

# ==========================================================
# 6) Hierarchical (Agglomerative) with Dendrogram
# ========================================================

from scipy.cluster.hierarchy import linkage, dendrogram, fcluster

#--------- Config knobs ----------
DENDRO_SAMPLE = 600     # subsample size for dendrogram (adjust based on RAM)
DENDRO_TRUNCATE = 25    # how many leaf clusters to show (for readability)
CUT_BY = 'k'            # 'k' to cut by number of clusters, 'dist' for distance threshold
CUT_K = best_k          # use KMeans' best_k for consistency
CUT_DIST = None         # if CUT_BY == 'dist', set a numeric distance (e.g., 50.0)
#-------------------------------

# Too many matches for dendrogram - need to sample some for running time
if len(X) > 600:
    sample_idx = np.random.choice(len(X), 600, replace=False)
    X_sample = X[sample_idx]
else:
    X_sample = X

# Ward linkage on the subsample

Z = linkage(X_sub, method='ward')

# Plot dendrogram (truncated)
plt.figure(figsize=(12, 6))
dendrogram(
    Z,
    truncate_mode='none',     # Change it to "'lastp'" if we want to have a better readbility here
    p=DENDRO_TRUNCATE,        # how many leaf clusters to display
    leaf_rotation=90.,
    leaf_font_size=10.,
    show_contracted=True,
)
plt.title('Hierarchical Clustering Dendrogram (Ward)')
plt.xlabel('Leaf clusters (truncated)')
plt.ylabel('Distance')
plt.tight_layout()
plt.show()

# Cut the tree to get cluster labels on the subsample
if CUT_BY == 'k':
    # Cut to get a desired number of clusters (like best_k)
    sub_labels = fcluster(Z, t=CUT_K, criterion='maxclust')
else:
    # Cut by distance threshold (horizontal line at CUT_DIST)
    if CUT_DIST is None:
        raise ValueError("Set CUT_DIST when CUT_BY == 'dist'")
    sub_labels = fcluster(Z, t=CUT_DIST, criterion='distance')

print(f"[Dendrogram] Produced {len(np.unique(sub_labels))} clusters on the dendrogram subsample.")

# Compare dendrogram clusters vs. KMeans (on the same subsample points)
#    This is just to eyeball consistency — not a formal evaluation.
plt.figure(figsize=(6,5))
sns.scatterplot(
    x=X_2d[dendro_idx, 0], y=X_2d[dendro_idx, 1],
    hue=sub_labels, palette='tab20', s=35, alpha=0.9
)
plt.title('Dendrogram cut clusters (PCA 2D, subsample)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# dendrogram-based labels for ALL rows (not just subsample):
#    Fit AgglomerativeClustering on the full X with the same settings.
hac_full = AgglomerativeClustering(n_clusters=CUT_K, linkage='ward')
hac_full_labels = hac_full.fit_predict(X)
data['cluster_hac_dendro'] = hac_full_labels

plt.figure(figsize=(6,5))
sns.scatterplot(x=X_2d[:,0], y=X_2d[:,1], hue=hac_full_labels, palette='tab10', s=35, alpha=0.85)
plt.title('Agglomerative clusters (Ward) — full data (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='cluster', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Quick size check
print("HAC (dendrogram-style) label counts:")
print(pd.Series(hac_full_labels).value_counts().sort_index())

# A bottom-up based algorithm with a different notion of Grouping.
#Giventhey’re similar to K‑Means, it strengthens confidence.

# --------------------------------------------
# 7)DBSCAN (density-based)
# ------------------------------------------
# k-distance plot to choose eps
neighbors = NearestNeighbors(n_neighbors=5)
neighbors_fit = neighbors.fit(X)
distances, indices = neighbors_fit.kneighbors(X)
distances = np.sort(distances[:, -1])

plt.figure(figsize=(6,4))
plt.plot(distances)
plt.title('k-distance plot (k=5) for DBSCAN eps selection')
plt.ylabel('distance')
plt.xlabel('sorted points')
plt.show()

dbscan = DBSCAN(eps=DBSCAN_EPS, min_samples=DBSCAN_MIN_SAMPLES)
db_labels = dbscan.fit_predict(X)
data['cluster_db'] = db_labels
print('DBSCAN label counts:\n', pd.Series(db_labels).value_counts().sort_index())

plt.figure(figsize=(6,5))
sns.scatterplot(x=X_2d[:,0], y=X_2d[:,1], hue=db_labels, palette='tab10', s=35, alpha=0.85)
plt.title('DBSCAN (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend(title='label', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0)
plt.tight_layout()
plt.show()

#DBSCAN finds irregular shapes and flags outliers automatically, which should be Good for football matches that don’t fit usual patterns.

# ------------------------------------------------
# 8) Relate clusters to outcomes
# -----------------------------------------------
if 'FT Result' in data.columns:
    ct = pd.crosstab(data['cluster_km'], data['FT Result'], normalize='index').round(3)
    print("[Info] FT Result distribution by KMeans cluster (row-normalized):")
    display(ct)

if 'FT_total_goals' in data.columns:
    print("[Info] Average FT_total_goals by KMeans cluster:")
    display(data.groupby('cluster_km')['FT_total_goals'].mean().round(3))


    #Shows whether clusters are practically meaningful.
    #for example, clusters with high shots/accuracy might have higher average FT_total_goals, or a particular cluster might see more home wins.

# -------------------------------------------------------
# 9) Use cluster ID as a feature in a supervised model
# -------------------------------------------------------
# Build a supervised dataset as before + cluster feature
rf_features = [
    'H Shots', 'A Shots', 'H SOT', 'A SOT',
    'H Fouls', 'A Fouls', 'H Yellow', 'A Yellow',
    'H Red', 'A Red', 'H Corners', 'A Corners',
    'cluster_km'  # newly added
]
rf_features = [c for c in rf_features if c in data.columns]

X_ml = data[rf_features]
y_ml = data['FT_total_goals'] if 'FT_total_goals' in data.columns else None

# Check if adding clusters actually helps prediction
X_train, X_test, y_train, y_test = train_test_split(X_ml, y_ml, test_size=0.2, random_state=42)
rf = RandomForestRegressor(n_estimators=200, random_state=42)  # 300 took forever
rf.fit(X_train, y_train)
r2_score = rf.score(X_test, y_test)
print(f"R-squared with clusters: {r2_score:.3f}")
# TODO: compare with baseline model without clusters

""" Clustering Section9

---


    An R² of 0.383 means the model explains 38.3% of the variance in FT_total_goals on the holdout set
"""

# ==========================
# 10 Evaluate cluster usefulness
# ==========================
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import numpy as np
import pandas as pd

RANDOM_STATE = 42

# 1) Define base features
base_feats = [
    'H Shots','A Shots','H SOT','A SOT',
    'H Fouls','A Fouls','H Yellow','A Yellow',
    'H Red','A Red','H Corners','A Corners'
]
base_feats = [c for c in base_feats if c in data.columns]

# 2) Target
y = data['FT_total_goals'].copy()

# 3) Two designs: without and with cluster
X_base = data[base_feats].copy()

if 'cluster_km' not in data.columns:
    raise ValueError("Missing 'cluster_km'. Run the clustering cell first.")

X_with_cluster = data[base_feats + ['cluster_km']].copy()

# 4) Train/test split (same split just for fair)
Xb_train, Xb_test, y_train, y_test = train_test_split(X_base, y, test_size=0.2, random_state=RANDOM_STATE)
Xc_train, Xc_test, _, _ = train_test_split(X_with_cluster, y, test_size=0.2, random_state=RANDOM_STATE)

rf_base = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
rf_base.fit(Xb_train, y_train)
r2_base = rf_base.score(Xb_test, y_test)

rf_cluster = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
rf_cluster.fit(Xc_train, y_train)
r2_cluster = rf_cluster.score(Xc_test, y_test)

print(f"[Eval] R^2 without cluster: {r2_base:.3f}")
print(f"[Eval] R^2 with cluster:    {r2_cluster:.3f}")
print(f"[Eval] Delta R^2 (with - without): {r2_cluster - r2_base:+.3f}")

# 5) Random-label control (should not help the explaination I assume)
rng = np.random.default_rng(RANDOM_STATE)
X_rand = X_with_cluster.copy()
X_rand['cluster_km'] = rng.permutation(X_rand['cluster_km'].values)  # shuffle labels

Xr_train, Xr_test, _, _ = train_test_split(X_rand, y, test_size=0.2, random_state=RANDOM_STATE)
rf_rand = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
rf_rand.fit(Xr_train, y_train)
r2_rand = rf_rand.score(Xr_test, y_test)
print(f"[Eval] R^2 with random cluster labels: {r2_rand:.3f}")

# 6) Importance diagnostics on the 'with cluster' model
feat_names = X_with_cluster.columns
imp = pd.Series(rf_cluster.feature_importances_, index=feat_names).sort_values(ascending=False)
print("\n[Eval] RF Feature Importances:")
print(imp.round(4))

perm = permutation_importance(rf_cluster, Xc_test, y_test, n_repeats=10, random_state=RANDOM_STATE, n_jobs=-1)
perm_imp = pd.Series(perm.importances_mean, index=feat_names).sort_values(ascending=False)
print("\n[Eval] Permutation Importances (test set):")
print(perm_imp.round(4))

# 7) quick leakage-safe recheck
# Re-run this clustering with INCLUDE_ENGINEERED=False before executing this block if need :/ .....
#if 'cluster_km_pure' in data.columns:
#    X_pure = data[base_feats + ['cluster_km_pure']]
#    Xp_train, Xp_test, _, _ = train_test_split(X_pure, y, test_size=0.2, random_state=RANDOM_STATE)
#    rf_pure = RandomForestRegressor(n_estimators=400, random_state=RANDOM_STATE, n_jobs=-1)
#    rf_pure.fit(Xp_train, y_train)
#    print(f"\n[Leakage-safe] R^2 with pure cluster (no target in clustering): {rf_pure.score(Xp_test, y_test):.3f}")
#else:
#    print("\n[Note] For a leakage-safe test, recompute clusters with INCLUDE_ENGINEERED=False and store as 'cluster_km_pure'.")
